#!/usr/bin/env bash
# MfAP standalone entrypoint (setup + launch).
# Usage:
#   bash mfap.sh          # install dependencies (and offer to launch)
#   bash mfap.sh --run    # launch only (skips install if already set up)
#   bash mfap.sh --force  # reinstall even if already set up
#   bash mfap.sh --run --force  # reinstall then launch

set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$APP_ROOT"

VENV_DIR="${APP_ROOT}/.venv"
RLIB_DIR="${APP_ROOT}/r-lib"
MARKER_FILE="${APP_ROOT}/.mfap_setup_complete"
REQUIREMENTS="${APP_ROOT}/requirements.txt"
RENVIRON="${APP_ROOT}/.Renviron"

DO_RUN=0
DO_FORCE=0
for arg in "$@"; do
  case "$arg" in
    --run) DO_RUN=1 ;;
    --force) DO_FORCE=1 ;;
    -h|--help)
      cat <<'EOF'
MfAP standalone entrypoint

  bash mfap.sh          First-time setup (install R/Python deps)
  bash mfap.sh --run    Launch the app (runs setup first if needed)
  bash mfap.sh --force  Reinstall dependencies

Requirements: R >= 4.4, Python 3.9–3.12 (3.9 recommended), bash.
EOF
      exit 0
      ;;
    *)
      echo "Unknown option: $arg (use --run, --force, or --help)" >&2
      exit 1
      ;;
  esac
done

log() { printf '%s\n' "$*"; }
err() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# Usage: check_prereqs [--quiet]
check_prereqs() {
  local quiet=0
  [[ "${1:-}" == "--quiet" ]] && quiet=1

  command -v Rscript >/dev/null 2>&1 || err "Rscript not found. Install R >= 4.4 and ensure Rscript is on PATH."
  local r_major r_minor
  r_major="$(Rscript -e 'cat(R.version$major)')"
  r_minor="$(Rscript -e 'cat(strsplit(R.version$minor, ".", fixed=TRUE)[[1]][1])')"
  if [[ "$r_major" -lt 4 ]] || { [[ "$r_major" -eq 4 ]] && [[ "$r_minor" -lt 4 ]]; }; then
    err "R >= 4.4 required (found ${r_major}.${r_minor})."
  fi

  PYTHON_BIN=""
  local candidate
  for candidate in python3.12 python3.11 python3.10 python3.9 python3; do
    if command -v "$candidate" >/dev/null 2>&1; then
      local ver
      ver="$("$candidate" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
      local major minor
      major="${ver%%.*}"
      minor="${ver#*.}"
      if [[ "$major" -eq 3 ]] && [[ "$minor" -ge 9 ]] && [[ "$minor" -le 12 ]]; then
        PYTHON_BIN="$(command -v "$candidate")"
        break
      fi
    fi
  done
  [[ -n "$PYTHON_BIN" ]] || err "Python 3.9–3.12 not found on PATH (TensorFlow 2.19 does not support 3.13+). Install e.g. python3.11 or python3.12."
  if [[ "$quiet" -eq 0 ]]; then
    log "Using Python: $PYTHON_BIN ($("$PYTHON_BIN" --version 2>&1))"
    log "Using R: $(Rscript --version 2>&1)"
  fi
}

write_renviron() {
  local py_path
  py_path="${VENV_DIR}/bin/python"
  [[ -x "$py_path" ]] || err "Expected venv python at $py_path"

  cat > "$RENVIRON" <<EOF
# Generated by mfap.sh for local standalone use.
RETICULATE_PYTHON=${py_path}
R_LIBS_USER=${RLIB_DIR}
EOF
  log "Wrote ${RENVIRON}"
}

install_python() {
  log "Creating Python virtualenv at ${VENV_DIR} ..."
  "$PYTHON_BIN" -m venv "$VENV_DIR"
  # shellcheck disable=SC1091
  source "${VENV_DIR}/bin/activate"
  python -m pip install --upgrade pip wheel
  log "Installing Python packages from requirements.txt ..."
  python -m pip install -r "$REQUIREMENTS"
  deactivate
}

install_r() {
  mkdir -p "$RLIB_DIR"
  log "Installing R packages into ${RLIB_DIR} ..."
  R_LIBS_USER="$RLIB_DIR" Rscript --vanilla -e '
    lib <- Sys.getenv("R_LIBS_USER")
    dir.create(lib, showWarnings = FALSE, recursive = TRUE)
    .libPaths(c(lib, .libPaths()))
    options(repos = c(CRAN = "https://cloud.r-project.org"))

    in_local <- function(pkg) {
      pkg %in% rownames(installed.packages(lib.loc = lib))
    }

    cran_pkgs <- c("shiny", "shinyjs", "DT", "stringr", "dplyr", "bslib", "reticulate")
    for (pkg in cran_pkgs) {
      if (!in_local(pkg)) {
        message("Installing ", pkg, " into ", lib, " ...")
        install.packages(pkg, lib = lib, quiet = TRUE)
      } else {
        message(pkg, " already in local library")
      }
    }
    if (!in_local("BiocManager")) {
      message("Installing BiocManager ...")
      install.packages("BiocManager", lib = lib, quiet = TRUE)
    }
    if (!in_local("Biostrings")) {
      message("Installing Biostrings (Bioconductor) ...")
      BiocManager::install("Biostrings", lib = lib, ask = FALSE, update = FALSE, force = TRUE)
    } else {
      message("Biostrings already in local library")
    }
    needed <- c(cran_pkgs, "Biostrings", "BiocManager")
    missing <- needed[!vapply(needed, in_local, logical(1))]
    if (length(missing) > 0) {
      stop("Failed to install into local library: ", paste(missing, collapse = ", "))
    }
    message("R package install OK")
  '
}

is_setup_complete() {
  [[ -f "$MARKER_FILE" ]] \
    && [[ -x "${VENV_DIR}/bin/python" ]] \
    && [[ -f "$RENVIRON" ]] \
    && [[ -d "${RLIB_DIR}/shiny" ]] \
    && [[ -d "${RLIB_DIR}/reticulate" ]] \
    && [[ -d "${RLIB_DIR}/Biostrings" ]]
}

run_setup() {
  [[ -f "$REQUIREMENTS" ]] || err "requirements.txt not found in ${APP_ROOT}"
  [[ -f "${APP_ROOT}/app.R" ]] || err "app.R not found in ${APP_ROOT}"

  check_prereqs
  install_python
  install_r
  write_renviron

  date -u +"%Y-%m-%dT%H:%M:%SZ" > "$MARKER_FILE"
  log ""
  log "Setup complete."
  log "Launch with:  bash mfap.sh --run"
}

launch_app() {
  check_prereqs --quiet
  [[ -f "$RENVIRON" ]] || err ".Renviron missing; run bash mfap.sh first."
  [[ -x "${VENV_DIR}/bin/python" ]] || err "Python venv missing; run bash mfap.sh first."

  # Ensure reticulate sees the pinned env even if R does not auto-load .Renviron
  # from a non-interactive Rscript session in all cases.
  export RETICULATE_PYTHON="${VENV_DIR}/bin/python"
  export R_LIBS_USER="${RLIB_DIR}"
  export TF_CPP_MIN_LOG_LEVEL="${TF_CPP_MIN_LOG_LEVEL:-2}"

  log "Starting MfAP … (Ctrl+C to stop)"
  # Quiet package attach noise / R-version build warnings / known bslib nav note.
  # Real errors and the "Listening on …" line still print.
  Rscript --vanilla -e "
    Sys.setenv(
      RETICULATE_PYTHON = '${VENV_DIR}/bin/python',
      R_LIBS_USER = '${RLIB_DIR}',
      TF_CPP_MIN_LOG_LEVEL = Sys.getenv('TF_CPP_MIN_LOG_LEVEL', unset = '2')
    )
    .libPaths(c('${RLIB_DIR}', .libPaths()))
    muffler <- function(w) {
      msg <- conditionMessage(w)
      if (grepl('was built under R version|Navigation containers expect', msg, perl = TRUE))
        invokeRestart('muffleWarning')
    }
    withCallingHandlers(
      suppressPackageStartupMessages(
        shiny::runApp('${APP_ROOT}', launch.browser = TRUE)
      ),
      warning = muffler
    )
  "
}

# --- main ---
if [[ "$DO_RUN" -eq 1 ]]; then
  if [[ "$DO_FORCE" -eq 1 ]] || ! is_setup_complete; then
    run_setup
  fi
  launch_app
else
  if [[ "$DO_FORCE" -eq 1 ]] || ! is_setup_complete; then
    run_setup
  else
    log "Setup already complete (use --force to reinstall)."
    log "Launch with:  bash mfap.sh --run"
  fi

  if [[ -t 0 ]]; then
    printf 'Launch MfAP now? [Y/N] '
    read -r reply || true
    case "$reply" in
      y|Y|yes|YES)
        launch_app
        ;;
    esac
  fi
fi
